### ISSUE TITLE
Two minor issues

### ISSUE THREAD

**Issue by lincolnfrias** [rafapereirabr/Brazilian_Census#1]
Awesome work! Extremely helpful. 
Two minor things:
1-  fwrite() is available only in the development version of data.table, so you need:
    install.packages("data.table", type = "source",
               repos = "http://Rdatatable.github.io/data.table")

2- Missing closing parentesis in: 
    fwrite(temp, file.path="./Dados_csv/censo2010_BRdom.csv"

By now, I run the code only for MG and it worked great. 

Thank you very much for putting it together.

**Comment by rafapereirabr** [comment]
Thanks for spotting those issues @lincolnfrias ! I've just corrected them.

abracos,

Rafael Pereira
