### ISSUE TITLE
Erro no script ou falta de conhecimento

### ISSUE THREAD

**Issue by JRodrigues27** [rafapereirabr/Brazilian_Census#2]
Olá Rafael, primeiro obrigado por compartilhar seu script.
Estou tentando roda-lo e no comando:
# apply function to read national data into 'temp'
temp <- rbindlist(lapply(data_files, readMOR))
setDT(temp)

responde o seguinte erro:
 Error in guess_types_(datasource, tokenizer, locale, n = guess_max) : 
  Begin offset (-2147483648) must be smaller than end offset (-2147483648) 

Para o script funcionar, é preciso modificar alguma outra entrada além do diretório de trabalho?

Desde já agradeço a atenção.

**Comment by rafapereirabr** [comment]
Oi Rodrigues. Obrigado por apontar o erro. Nunca tinha visto esse erro antes. Nao sei o que pode estar causando.

Minha sugestao eh que voce passe a utilizar o pacote `microdadosBrasil` >>> [link](https://github.com/lucasmation/microdadosBrasil/). Esse pacote foi desenvolvido pelo Lucas Mation (Ipea) para fazer download e leitura dos microdades de varias bases de dados publicas no Brasil, incluindo censos e pnads do IBGE. O pacote ja incorporou algumas das solucoes desse meu codigo que aumentam muito a velocidade da leitura dos dados.

**Comment by JRodrigues27** [comment]
Obrigado!
Vou tentar.
